"""initial schema

Revision ID: 9df52d75134b
Revises:
Create Date: 2026-09-12 18:21:39.250356
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9df52d75134b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_tier",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "contact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("linkedin_url", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("headline", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=False),
        sa.Column("current_company", sa.String(length=120), nullable=False),
        sa.Column("current_title", sa.String(length=160), nullable=False),
        sa.Column("job_family", sa.String(length=40), nullable=False),
        sa.Column("seniority", sa.String(length=20), nullable=False),
        sa.Column("experiences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("education", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skills", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("enrichment_source", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("linkedin_url"),
    )
    op.create_index(
        "ix_contact_education_gin", "contact", ["education"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_contact_experiences_gin",
        "contact",
        ["experiences"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_contact_skills_gin", "contact", ["skills"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("department", sa.String(length=120), nullable=False),
        sa.Column("team", sa.String(length=120), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("slack_user_id", sa.String(length=32), nullable=True),
        sa.Column("experiences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("education", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ashby_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("department", sa.String(length=120), nullable=False),
        sa.Column("team", sa.String(length=120), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("is_remote", sa.Boolean(), nullable=False),
        sa.Column("employment_type", sa.String(length=40), nullable=False),
        sa.Column("description_html", sa.Text(), nullable=False),
        sa.Column("description_plain", sa.Text(), nullable=False),
        sa.Column("job_url", sa.String(length=300), nullable=False),
        sa.Column("apply_url", sa.String(length=300), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("required_skills", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("job_family", sa.String(length=40), nullable=False),
        sa.Column("seniority", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ashby_id"),
    )
    op.create_table(
        "school_tier",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "slack_event",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "connection",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("connected_on", sa.Date(), nullable=False),
        sa.Column("strength", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("strength_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_id", "contact_id"),
    )
    op.create_index(
        "ix_connection_contact_strength", "connection", ["contact_id", "strength"], unique=False
    )
    op.create_table(
        "match_score",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "contact_id"),
    )
    op.create_index("ix_match_score_role_score", "match_score", ["role_id", "score"], unique=False)
    op.create_table(
        "referral_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("outreach_casual", sa.Text(), nullable=False),
        sa.Column("outreach_formal", sa.Text(), nullable=False),
        sa.Column("closed_outcome", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_referral_request_status", "referral_request", ["status"], unique=False)
    op.create_index(
        "uq_active_request_per_contact",
        "referral_request",
        ["contact_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.create_table(
        "outreach_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("recipient", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("external_channel_id", sa.String(length=32), nullable=True),
        sa.Column("external_ts", sa.String(length=32), nullable=True),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(["request_id"], ["referral_request.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outreach_message_request_id"), "outreach_message", ["request_id"], unique=False
    )
    op.create_table(
        "referral_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["request_id"], ["referral_request.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_event_request_id"), "referral_event", ["request_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referral_event_request_id"), table_name="referral_event")
    op.drop_table("referral_event")
    op.drop_index(op.f("ix_outreach_message_request_id"), table_name="outreach_message")
    op.drop_table("outreach_message")
    op.drop_index(
        "uq_active_request_per_contact",
        table_name="referral_request",
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.drop_index("ix_referral_request_status", table_name="referral_request")
    op.drop_table("referral_request")
    op.drop_index("ix_match_score_role_score", table_name="match_score")
    op.drop_table("match_score")
    op.drop_index("ix_connection_contact_strength", table_name="connection")
    op.drop_table("connection")
    op.drop_table("slack_event")
    op.drop_table("school_tier")
    op.drop_table("role")
    op.drop_table("employee")
    op.drop_index("ix_contact_skills_gin", table_name="contact", postgresql_using="gin")
    op.drop_index("ix_contact_experiences_gin", table_name="contact", postgresql_using="gin")
    op.drop_index("ix_contact_education_gin", table_name="contact", postgresql_using="gin")
    op.drop_table("contact")
    op.drop_table("company_tier")
    # ### end Alembic commands ###
