"""Curated reference data for the synthetic seed. Names are canonical: the tier tables, the
generator and the filters all use exactly these spellings."""

from __future__ import annotations

from typing import Final

COMPANY_TIERS: Final[dict[str, int]] = {
    # Tier 1: target companies
    "Google": 1,
    "Meta": 1,
    "Stripe": 1,
    "OpenAI": 1,
    "Anthropic": 1,
    "Apple": 1,
    "Netflix": 1,
    "Databricks": 1,
    "Airbnb": 1,
    "Figma": 1,
    "Scale AI": 1,
    "Vercel": 1,
    "Snowflake": 1,
    "Nvidia": 1,
    "Palantir": 1,
    "DeepMind": 1,
    # Tier 2
    "Coinbase": 2,
    "Notion": 2,
    "Ramp": 2,
    "Brex": 2,
    "Plaid": 2,
    "Datadog": 2,
    "Cloudflare": 2,
    "Dropbox": 2,
    "Atlassian": 2,
    "Rippling": 2,
    "Linear": 2,
    "Retool": 2,
    "Replit": 2,
    "Hugging Face": 2,
    "Cohere": 2,
    "Twilio": 2,
    "Shopify": 2,
    "Uber": 2,
    "Microsoft": 2,
    "Amazon": 2,
    "Salesforce": 2,
    "Pinterest": 2,
    "DoorDash": 2,
    "Instacart": 2,
    # Tier 3
    "Oracle": 3,
    "IBM": 3,
    "Accenture": 3,
    "Deloitte": 3,
    "Capital One": 3,
    "JPMorgan": 3,
    "Cisco": 3,
    "Intel": 3,
    "Workday": 3,
    "ServiceNow": 3,
    "Zendesk": 3,
    "HubSpot": 3,
    "Okta": 3,
    "Gusto": 3,
    "Robinhood": 3,
    "Affirm": 3,
    "Lyft": 3,
    "Box": 3,
}

SCHOOL_TIERS: Final[dict[str, int]] = {
    # Tier 1 (15)
    "MIT": 1,
    "Stanford University": 1,
    "Carnegie Mellon University": 1,
    "UC Berkeley": 1,
    "Caltech": 1,
    "Harvard University": 1,
    "Princeton University": 1,
    "University of Waterloo": 1,
    "University of Illinois Urbana-Champaign": 1,
    "Georgia Tech": 1,
    "Cornell University": 1,
    "University of Washington": 1,
    "University of Toronto": 1,
    "University of Oxford": 1,
    "University of Cambridge": 1,
    # Tier 2 (20)
    "UCLA": 2,
    "UT Austin": 2,
    "University of Michigan": 2,
    "Columbia University": 2,
    "Yale University": 2,
    "University of Pennsylvania": 2,
    "Brown University": 2,
    "Duke University": 2,
    "NYU": 2,
    "USC": 2,
    "UC San Diego": 2,
    "Purdue University": 2,
    "University of Maryland": 2,
    "UMass Amherst": 2,
    "ETH Zurich": 2,
    "IIT Bombay": 2,
    "IIT Delhi": 2,
    "Tsinghua University": 2,
    "National University of Singapore": 2,
    "University of Wisconsin-Madison": 2,
    # Tier 3 (15)
    "Northeastern University": 3,
    "Boston University": 3,
    "Rutgers University": 3,
    "Penn State": 3,
    "Ohio State University": 3,
    "Arizona State University": 3,
    "UC Davis": 3,
    "UC Irvine": 3,
    "University of Florida": 3,
    "Virginia Tech": 3,
    "Texas A&M": 3,
    "University of Minnesota": 3,
    "University of Colorado Boulder": 3,
    "Rochester Institute of Technology": 3,
    "University of British Columbia": 3,
}

EMPLOYER: Final[str] = "Cognition"

# title -> seniority, per family. Titles are used verbatim for contacts and employees.
TITLE_LADDERS: Final[dict[str, tuple[tuple[str, str], ...]]] = {
    "engineering": (
        ("Software Engineer", "mid"),
        ("Senior Software Engineer", "senior"),
        ("Staff Software Engineer", "staff"),
        ("Engineering Manager", "lead"),
        ("Principal Engineer", "lead"),
        ("Software Engineer, New Grad", "junior"),
        ("Full Stack Engineer", "mid"),
        ("Senior Backend Engineer", "senior"),
        ("Senior Frontend Engineer", "senior"),
    ),
    "ml_research": (
        ("Research Engineer", "mid"),
        ("Senior Research Engineer", "senior"),
        ("Research Scientist", "senior"),
        ("Staff Research Scientist", "staff"),
        ("Machine Learning Engineer", "mid"),
        ("Senior Machine Learning Engineer", "senior"),
        ("ML Research Lead", "lead"),
    ),
    "infrastructure": (
        ("Site Reliability Engineer", "mid"),
        ("Senior Site Reliability Engineer", "senior"),
        ("Infrastructure Engineer", "mid"),
        ("Senior Infrastructure Engineer", "senior"),
        ("Staff Infrastructure Engineer", "staff"),
        ("Platform Engineer", "mid"),
        ("DevOps Engineer", "mid"),
        ("Infrastructure Lead", "lead"),
    ),
    "security": (
        ("Security Engineer", "mid"),
        ("Senior Security Engineer", "senior"),
        ("Staff Security Engineer", "staff"),
        ("Security Lead", "lead"),
    ),
    "data": (
        ("Data Engineer", "mid"),
        ("Senior Data Engineer", "senior"),
        ("Analytics Engineer", "mid"),
        ("Data Scientist", "mid"),
        ("Senior Data Scientist", "senior"),
        ("Staff Data Engineer", "staff"),
    ),
    "product": (
        ("Product Manager", "mid"),
        ("Senior Product Manager", "senior"),
        ("Group Product Manager", "lead"),
        ("Director of Product", "director"),
    ),
    "design": (
        ("Product Designer", "mid"),
        ("Senior Product Designer", "senior"),
        ("Staff Product Designer", "staff"),
        ("Design Lead", "lead"),
    ),
    "customer_engineering": (
        ("Solutions Engineer", "mid"),
        ("Senior Solutions Engineer", "senior"),
        ("Forward Deployed Engineer", "mid"),
        ("Senior Forward Deployed Engineer", "senior"),
        ("Deployed Engineer", "mid"),
        ("Support Engineer", "junior"),
        ("Sales Engineer", "mid"),
        ("Solutions Architect", "senior"),
    ),
    "sales": (
        ("Account Executive", "mid"),
        ("Senior Account Executive", "senior"),
        ("Enterprise Account Executive", "senior"),
        ("Account Director", "lead"),
        ("Sales Development Representative", "junior"),
        ("Regional Sales Director", "director"),
        ("Head of Partnerships", "director"),
        ("Partner Manager", "mid"),
        ("VP of Sales", "vp"),
    ),
    "marketing": (
        ("Product Marketing Manager", "mid"),
        ("Senior Product Marketing Manager", "senior"),
        ("Demand Generation Manager", "mid"),
        ("Field Marketing Manager", "mid"),
        ("Brand Marketing Lead", "lead"),
        ("Developer Advocate", "mid"),
        ("Head of Marketing", "director"),
        ("Content Marketing Manager", "mid"),
    ),
    "recruiting": (
        ("Technical Recruiter", "mid"),
        ("Senior Technical Recruiter", "senior"),
        ("Recruiting Coordinator", "junior"),
        ("Head of Talent", "director"),
        ("GTM Recruiter", "mid"),
    ),
    "people_ops": (
        ("People Operations Manager", "lead"),
        ("HR Business Partner", "senior"),
        ("People Operations Coordinator", "junior"),
        ("Payroll Manager", "lead"),
    ),
    "finance_legal": (
        ("Commercial Counsel", "senior"),
        ("Legal Operations Manager", "lead"),
        ("Finance Manager", "lead"),
        ("FP&A Analyst", "mid"),
        ("Controller", "director"),
    ),
    "operations": (
        ("Business Operations Manager", "lead"),
        ("Chief of Staff", "director"),
        ("Executive Assistant", "mid"),
        ("IT Engineer", "mid"),
        ("Operations Lead", "lead"),
        ("Workplace Coordinator", "junior"),
    ),
}

# Weighted family mix for contacts (networks of a mostly-engineering company).
CONTACT_FAMILY_WEIGHTS: Final[dict[str, int]] = {
    "engineering": 26,
    "infrastructure": 10,
    "ml_research": 10,
    "customer_engineering": 8,
    "sales": 12,
    "marketing": 6,
    "data": 5,
    "product": 5,
    "security": 3,
    "design": 3,
    "recruiting": 4,
    "people_ops": 2,
    "finance_legal": 2,
    "operations": 4,
}

# Exact employee mix (sums to 40; the generator scales if a different count is requested).
EMPLOYEE_FAMILY_MIX: Final[dict[str, int]] = {
    "engineering": 14,
    "ml_research": 6,
    "infrastructure": 4,
    "customer_engineering": 5,
    "sales": 4,
    "marketing": 2,
    "recruiting": 2,
    "product": 1,
    "design": 1,
    "operations": 1,
}

DEPARTMENT_BY_FAMILY: Final[dict[str, str]] = {
    "engineering": "Research & Development",
    "ml_research": "Research & Development",
    "infrastructure": "Research & Development",
    "security": "Research & Development",
    "data": "Research & Development",
    "product": "Research & Development",
    "design": "Research & Development",
    "customer_engineering": "Customer Engineering",
    "sales": "Sales",
    "marketing": "Marketing",
    "recruiting": "General & Administrative",
    "people_ops": "General & Administrative",
    "finance_legal": "General & Administrative",
    "operations": "General & Administrative",
}

TEAMS: Final[tuple[str, ...]] = (
    "Infrastructure",
    "Payments",
    "Growth",
    "Platform",
    "Search",
    "Ads",
    "Core ML",
    "Developer Products",
    "Enterprise",
    "Security",
    "Data Platform",
    "Identity",
    "Mobile",
    "Applied AI",
    "Field Engineering",
)

LOCATIONS: Final[tuple[tuple[str, int], ...]] = (
    ("San Francisco", 34),
    ("New York City", 18),
    ("Seattle", 10),
    ("Austin", 6),
    ("Los Angeles", 5),
    ("Boston", 5),
    ("London", 6),
    ("Toronto", 5),
    ("Singapore", 3),
    ("Tokyo", 3),
    ("Remote", 5),
)

DEGREES: Final[tuple[tuple[str, str, int], ...]] = (
    # degree, field, weight
    ("BS", "Computer Science", 40),
    ("BS", "Electrical Engineering", 10),
    ("BS", "Mathematics", 6),
    ("BA", "Economics", 8),
    ("BS", "Physics", 4),
    ("BA", "Business Administration", 8),
    ("BS", "Data Science", 5),
    ("BA", "Communications", 4),
    ("BS", "Information Systems", 5),
    ("BA", "Psychology", 3),
    ("BS", "Mechanical Engineering", 4),
    ("BA", "Political Science", 3),
)

GRAD_DEGREES: Final[tuple[tuple[str, str, int], ...]] = (
    ("MS", "Computer Science", 50),
    ("PhD", "Computer Science", 15),
    ("MBA", "Business", 20),
    ("MS", "Machine Learning", 10),
    ("JD", "Law", 5),
)
